#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("HQI.Resource", IsApplication=true)]

namespace HQI
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f060001
			public const int registration_states_array = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int registration_title_array = 2131099648;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int cellback = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int official_green = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int official_orange = 2130968577;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int CustomSelector = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070064
			public const int Date_of_Birth_profile = 2131165284;
			
			// aapt resource value: 0x7f070002
			public const int Image = 2131165186;
			
			// aapt resource value: 0x7f07003a
			public const int List5 = 2131165242;
			
			// aapt resource value: 0x7f070003
			public const int Text = 2131165187;
			
			// aapt resource value: 0x7f07000f
			public const int Text1 = 2131165199;
			
			// aapt resource value: 0x7f070011
			public const int Text2 = 2131165201;
			
			// aapt resource value: 0x7f070004
			public const int Text_layout = 2131165188;
			
			// aapt resource value: 0x7f070007
			public const int Text_layout2 = 2131165191;
			
			// aapt resource value: 0x7f070001
			public const int Text_layout_base = 2131165185;
			
			// aapt resource value: 0x7f070010
			public const int Text_layout_base2 = 2131165200;
			
			// aapt resource value: 0x7f07002b
			public const int account_button = 2131165227;
			
			// aapt resource value: 0x7f070020
			public const int account_header_layout = 2131165216;
			
			// aapt resource value: 0x7f070021
			public const int account_number = 2131165217;
			
			// aapt resource value: 0x7f070035
			public const int btnForgotPassword = 2131165237;
			
			// aapt resource value: 0x7f070030
			public const int btnLogIn = 2131165232;
			
			// aapt resource value: 0x7f070033
			public const int btnRegister = 2131165235;
			
			// aapt resource value: 0x7f070053
			public const int chkAgreeTerms = 2131165267;
			
			// aapt resource value: 0x7f070063
			public const int datebirth_layout = 2131165283;
			
			// aapt resource value: 0x7f07002e
			public const int editText1 = 2131165230;
			
			// aapt resource value: 0x7f07002f
			public const int editText2 = 2131165231;
			
			// aapt resource value: 0x7f070058
			public const int email_layout = 2131165272;
			
			// aapt resource value: 0x7f070059
			public const int emailaddress_profile = 2131165273;
			
			// aapt resource value: 0x7f07001d
			public const int fgp_btnLogin = 2131165213;
			
			// aapt resource value: 0x7f07001c
			public const int fgp_btnRetrieve = 2131165212;
			
			// aapt resource value: 0x7f070060
			public const int firstname_layout = 2131165280;
			
			// aapt resource value: 0x7f070061
			public const int firstname_profile = 2131165281;
			
			// aapt resource value: 0x7f070034
			public const int forgot_layout = 2131165236;
			
			// aapt resource value: 0x7f070029
			public const int games_button = 2131165225;
			
			// aapt resource value: 0x7f070028
			public const int go_to_web_layout = 2131165224;
			
			// aapt resource value: 0x7f07001e
			public const int header_layout = 2131165214;
			
			// aapt resource value: 0x7f070055
			public const int header_layout_profile = 2131165269;
			
			// aapt resource value: 0x7f07001f
			public const int header_myaccount = 2131165215;
			
			// aapt resource value: 0x7f070066
			public const int homeaddress1_layout = 2131165286;
			
			// aapt resource value: 0x7f070067
			public const int homeaddress1_layout_hori_1 = 2131165287;
			
			// aapt resource value: 0x7f070068
			public const int homeaddress_profile = 2131165288;
			
			// aapt resource value: 0x7f070019
			public const int imagelayout = 2131165209;
			
			// aapt resource value: 0x7f07002c
			public const int info_button = 2131165228;
			
			// aapt resource value: 0x7f070027
			public const int infocontactbtn_layout = 2131165223;
			
			// aapt resource value: 0x7f070022
			public const int inforcontact_layout = 2131165218;
			
			// aapt resource value: 0x7f07005d
			public const int lastname_layout = 2131165277;
			
			// aapt resource value: 0x7f07005e
			public const int lastname_profile = 2131165278;
			
			// aapt resource value: 0x7f070018
			public const int linearLayout2 = 2131165208;
			
			// aapt resource value: 0x7f07001a
			public const int logo = 2131165210;
			
			// aapt resource value: 0x7f07002d
			public const int logout_button = 2131165229;
			
			// aapt resource value: 0x7f070036
			public const int main_separator1 = 2131165238;
			
			// aapt resource value: 0x7f070000
			public const int myTitle = 2131165184;
			
			// aapt resource value: 0x7f070075
			public const int occupation_layout = 2131165301;
			
			// aapt resource value: 0x7f070076
			public const int occupation_profile = 2131165302;
			
			// aapt resource value: 0x7f070016
			public const int parentlayout = 2131165206;
			
			// aapt resource value: 0x7f070056
			public const int profile_intro = 2131165270;
			
			// aapt resource value: 0x7f070054
			public const int r_btnNext = 2131165268;
			
			// aapt resource value: 0x7f070048
			public const int r_datePickerDateOfBirth = 2131165256;
			
			// aapt resource value: 0x7f07004a
			public const int r_editTextAddressLine1 = 2131165258;
			
			// aapt resource value: 0x7f07004c
			public const int r_editTextCountry = 2131165260;
			
			// aapt resource value: 0x7f070049
			public const int r_editTextEmail = 2131165257;
			
			// aapt resource value: 0x7f070044
			public const int r_editTextFirstName = 2131165252;
			
			// aapt resource value: 0x7f070050
			public const int r_editTextOccupation = 2131165264;
			
			// aapt resource value: 0x7f070051
			public const int r_editTextPassword1 = 2131165265;
			
			// aapt resource value: 0x7f070052
			public const int r_editTextPassword2 = 2131165266;
			
			// aapt resource value: 0x7f070043
			public const int r_editTextSurname = 2131165251;
			
			// aapt resource value: 0x7f07004d
			public const int r_editTextTelephone = 2131165261;
			
			// aapt resource value: 0x7f07004e
			public const int r_editTextTelephone2 = 2131165262;
			
			// aapt resource value: 0x7f07004f
			public const int r_editTextTelephone3 = 2131165263;
			
			// aapt resource value: 0x7f07003d
			public const int r_linearLayout1 = 2131165245;
			
			// aapt resource value: 0x7f07003f
			public const int r_linearLayout2 = 2131165247;
			
			// aapt resource value: 0x7f070040
			public const int r_myButton = 2131165248;
			
			// aapt resource value: 0x7f070045
			public const int r_rdoGender = 2131165253;
			
			// aapt resource value: 0x7f070046
			public const int r_rdoGenderF = 2131165254;
			
			// aapt resource value: 0x7f070047
			public const int r_rdoGenderM = 2131165255;
			
			// aapt resource value: 0x7f07000a
			public const int r_rdoResponse1 = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int r_rdoResponse2 = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int r_rdoResponse3 = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int r_rdoResponse4 = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public const int r_rdoResponse5 = 2131165198;
			
			// aapt resource value: 0x7f070009
			public const int r_rdoResponses = 2131165193;
			
			// aapt resource value: 0x7f07003e
			public const int r_scrollView1 = 2131165246;
			
			// aapt resource value: 0x7f07004b
			public const int r_spinnerState = 2131165259;
			
			// aapt resource value: 0x7f070042
			public const int r_spinnerTitle = 2131165250;
			
			// aapt resource value: 0x7f070041
			public const int r_textView1 = 2131165249;
			
			// aapt resource value: 0x7f070031
			public const int reg_forgot_layout = 2131165233;
			
			// aapt resource value: 0x7f070032
			public const int reg_layout = 2131165234;
			
			// aapt resource value: 0x7f07002a
			public const int result_button = 2131165226;
			
			// aapt resource value: 0x7f070017
			public const int scrollView1 = 2131165207;
			
			// aapt resource value: 0x7f070038
			public const int separator = 2131165240;
			
			// aapt resource value: 0x7f070057
			public const int separator2 = 2131165271;
			
			// aapt resource value: 0x7f070078
			public const int separator3 = 2131165304;
			
			// aapt resource value: 0x7f07003b
			public const int separator4 = 2131165243;
			
			// aapt resource value: 0x7f07003c
			public const int spinnerHospitals = 2131165244;
			
			// aapt resource value: 0x7f07006a
			public const int state_layout = 2131165290;
			
			// aapt resource value: 0x7f07006b
			public const int state_profile = 2131165291;
			
			// aapt resource value: 0x7f070037
			public const int survey_title = 2131165239;
			
			// aapt resource value: 0x7f07006c
			public const int telephone1_layout = 2131165292;
			
			// aapt resource value: 0x7f07006d
			public const int telephone1_profile = 2131165293;
			
			// aapt resource value: 0x7f07006f
			public const int telephone2_layout = 2131165295;
			
			// aapt resource value: 0x7f070070
			public const int telephone2_profile = 2131165296;
			
			// aapt resource value: 0x7f070072
			public const int telephone3_layout = 2131165298;
			
			// aapt resource value: 0x7f070073
			public const int telephone3_profile = 2131165299;
			
			// aapt resource value: 0x7f07005b
			public const int title_layout = 2131165275;
			
			// aapt resource value: 0x7f07005c
			public const int title_profile = 2131165276;
			
			// aapt resource value: 0x7f070024
			public const int txtCR = 2131165220;
			
			// aapt resource value: 0x7f070026
			public const int txtCS = 2131165222;
			
			// aapt resource value: 0x7f07001b
			public const int txtEmail = 2131165211;
			
			// aapt resource value: 0x7f070014
			public const int txtHospitalName = 2131165204;
			
			// aapt resource value: 0x7f070013
			public const int txtHospitalRef = 2131165203;
			
			// aapt resource value: 0x7f070008
			public const int txtRatingResponseText = 2131165192;
			
			// aapt resource value: 0x7f070006
			public const int txtRatingText = 2131165190;
			
			// aapt resource value: 0x7f070025
			public const int txtSales = 2131165221;
			
			// aapt resource value: 0x7f070005
			public const int txtSerial = 2131165189;
			
			// aapt resource value: 0x7f070015
			public const int txtSurveyDate = 2131165205;
			
			// aapt resource value: 0x7f070012
			public const int txtSurveyNumber = 2131165202;
			
			// aapt resource value: 0x7f070023
			public const int txtTitle = 2131165219;
			
			// aapt resource value: 0x7f070069
			public const int upd_AddressLine1 = 2131165289;
			
			// aapt resource value: 0x7f070065
			public const int upd_DateOfBirth = 2131165285;
			
			// aapt resource value: 0x7f07005a
			public const int upd_Email = 2131165274;
			
			// aapt resource value: 0x7f070062
			public const int upd_FirstName = 2131165282;
			
			// aapt resource value: 0x7f07005f
			public const int upd_LastName = 2131165279;
			
			// aapt resource value: 0x7f070077
			public const int upd_Occupation = 2131165303;
			
			// aapt resource value: 0x7f07006e
			public const int upd_Telephone1 = 2131165294;
			
			// aapt resource value: 0x7f070071
			public const int upd_Telephone2 = 2131165297;
			
			// aapt resource value: 0x7f070074
			public const int upd_Telephone3 = 2131165300;
			
			// aapt resource value: 0x7f07007a
			public const int upd_btnCancel = 2131165306;
			
			// aapt resource value: 0x7f070079
			public const int upd_btnSaveProfile = 2131165305;
			
			// aapt resource value: 0x7f070039
			public const int update_profile_layout = 2131165241;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int _Custom_Title = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int _ListView_NewSurveyDetail = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int _ListView_StandardFont = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int _ListView_SurveyHistory = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int _ListView_SurveyHistoryDetail = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int ForgotPasswordLayout = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int InfoContactLayout = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Main = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int MySurveysDetailLayout = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int MySurveysLayout = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int NewSurveyLayout = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int Register = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int UpdateProfileLayout = 2130903052;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050005
			public const int alert_dismissal_phrase = 2131034117;
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int app_title = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int company_website = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int customer_support_email = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			// aapt resource value: 0x7f050008
			public const int hospital_prompt = 2131034120;
			
			// aapt resource value: 0x7f050006
			public const int registration_states_prompt = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int registration_title_prompt = 2131034119;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
