//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HQI.WSHQIWebService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="HQIWebServiceSoap", Namespace="http://www.axialabs.com/")]
    public partial class HQIWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public HQIWebService() {
            this.Url = "http://50.56.227.124/hqiwebservice/default.asmx";
        }
        
        public HQIWebService(string url) {
            this.Url = url;
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.axialabs.com/route_Patient_AddNew", RequestNamespace="http://www.axialabs.com/", ResponseNamespace="http://www.axialabs.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public WS_Patient_AddNew_Response route_Patient_AddNew(WS_Patient_AddNew_Request patientProfile) {
            object[] results = this.Invoke("route_Patient_AddNew", new object[] {
                        patientProfile});
            return ((WS_Patient_AddNew_Response)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginroute_Patient_AddNew(WS_Patient_AddNew_Request patientProfile, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("route_Patient_AddNew", new object[] {
                        patientProfile}, callback, asyncState);
        }
        
        /// <remarks/>
        public WS_Patient_AddNew_Response Endroute_Patient_AddNew(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((WS_Patient_AddNew_Response)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.axialabs.com/route_Login", RequestNamespace="http://www.axialabs.com/", ResponseNamespace="http://www.axialabs.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public WS_Login_Response route_Login(WS_Login_Request loginDetails) {
            object[] results = this.Invoke("route_Login", new object[] {
                        loginDetails});
            return ((WS_Login_Response)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginroute_Login(WS_Login_Request loginDetails, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("route_Login", new object[] {
                        loginDetails}, callback, asyncState);
        }
        
        /// <remarks/>
        public WS_Login_Response Endroute_Login(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((WS_Login_Response)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.axialabs.com/route_Patient_GetByPatientRef", RequestNamespace="http://www.axialabs.com/", ResponseNamespace="http://www.axialabs.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public WS_Patient_GetByPatientRef_Response route_Patient_GetByPatientRef(WS_Patient_GetByPatientRef_Request patientIdentifier) {
            object[] results = this.Invoke("route_Patient_GetByPatientRef", new object[] {
                        patientIdentifier});
            return ((WS_Patient_GetByPatientRef_Response)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginroute_Patient_GetByPatientRef(WS_Patient_GetByPatientRef_Request patientIdentifier, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("route_Patient_GetByPatientRef", new object[] {
                        patientIdentifier}, callback, asyncState);
        }
        
        /// <remarks/>
        public WS_Patient_GetByPatientRef_Response Endroute_Patient_GetByPatientRef(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((WS_Patient_GetByPatientRef_Response)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.axialabs.com/route_Patient_GetByEmail", RequestNamespace="http://www.axialabs.com/", ResponseNamespace="http://www.axialabs.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public WS_Patient_GetByEmail_Response route_Patient_GetByEmail(WS_Patient_GetByEmail_Request patientIdentifier) {
            object[] results = this.Invoke("route_Patient_GetByEmail", new object[] {
                        patientIdentifier});
            return ((WS_Patient_GetByEmail_Response)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginroute_Patient_GetByEmail(WS_Patient_GetByEmail_Request patientIdentifier, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("route_Patient_GetByEmail", new object[] {
                        patientIdentifier}, callback, asyncState);
        }
        
        /// <remarks/>
        public WS_Patient_GetByEmail_Response Endroute_Patient_GetByEmail(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((WS_Patient_GetByEmail_Response)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.axialabs.com/route_Patient_Update", RequestNamespace="http://www.axialabs.com/", ResponseNamespace="http://www.axialabs.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public WS_Patient_Update_Response route_Patient_Update(WS_Patient_Update_Request patientProfile) {
            object[] results = this.Invoke("route_Patient_Update", new object[] {
                        patientProfile});
            return ((WS_Patient_Update_Response)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginroute_Patient_Update(WS_Patient_Update_Request patientProfile, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("route_Patient_Update", new object[] {
                        patientProfile}, callback, asyncState);
        }
        
        /// <remarks/>
        public WS_Patient_Update_Response Endroute_Patient_Update(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((WS_Patient_Update_Response)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.axialabs.com/route_HospitalRatingAssessment_AddNew", RequestNamespace="http://www.axialabs.com/", ResponseNamespace="http://www.axialabs.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public WS_HospitalRatingAssessment_AddNew_Response route_HospitalRatingAssessment_AddNew(WS_HospitalRatingAssessment_AddNew_Request hospitalRatingAssessment) {
            object[] results = this.Invoke("route_HospitalRatingAssessment_AddNew", new object[] {
                        hospitalRatingAssessment});
            return ((WS_HospitalRatingAssessment_AddNew_Response)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginroute_HospitalRatingAssessment_AddNew(WS_HospitalRatingAssessment_AddNew_Request hospitalRatingAssessment, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("route_HospitalRatingAssessment_AddNew", new object[] {
                        hospitalRatingAssessment}, callback, asyncState);
        }
        
        /// <remarks/>
        public WS_HospitalRatingAssessment_AddNew_Response Endroute_HospitalRatingAssessment_AddNew(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((WS_HospitalRatingAssessment_AddNew_Response)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.axialabs.com/route_HospitalRatingResponse_Get", RequestNamespace="http://www.axialabs.com/", ResponseNamespace="http://www.axialabs.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public WS_HospitalRatingResponse_Get_Response route_HospitalRatingResponse_Get(WS_HospitalRatingResponse_Get_Request hospitalRatingResponseIdentifier) {
            object[] results = this.Invoke("route_HospitalRatingResponse_Get", new object[] {
                        hospitalRatingResponseIdentifier});
            return ((WS_HospitalRatingResponse_Get_Response)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginroute_HospitalRatingResponse_Get(WS_HospitalRatingResponse_Get_Request hospitalRatingResponseIdentifier, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("route_HospitalRatingResponse_Get", new object[] {
                        hospitalRatingResponseIdentifier}, callback, asyncState);
        }
        
        /// <remarks/>
        public WS_HospitalRatingResponse_Get_Response Endroute_HospitalRatingResponse_Get(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((WS_HospitalRatingResponse_Get_Response)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.axialabs.com/route_HospitalRatings_GetAll", RequestNamespace="http://www.axialabs.com/", ResponseNamespace="http://www.axialabs.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public WS_HospitalRatings_GetAll_Response route_HospitalRatings_GetAll() {
            object[] results = this.Invoke("route_HospitalRatings_GetAll", new object[0]);
            return ((WS_HospitalRatings_GetAll_Response)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginroute_HospitalRatings_GetAll(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("route_HospitalRatings_GetAll", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public WS_HospitalRatings_GetAll_Response Endroute_HospitalRatings_GetAll(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((WS_HospitalRatings_GetAll_Response)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.axialabs.com/route_Hospitals_GetAll", RequestNamespace="http://www.axialabs.com/", ResponseNamespace="http://www.axialabs.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public WS_Hospitals_GetAll_Response route_Hospitals_GetAll() {
            object[] results = this.Invoke("route_Hospitals_GetAll", new object[0]);
            return ((WS_Hospitals_GetAll_Response)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginroute_Hospitals_GetAll(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("route_Hospitals_GetAll", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public WS_Hospitals_GetAll_Response Endroute_Hospitals_GetAll(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((WS_Hospitals_GetAll_Response)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.axialabs.com/route_HospitalRatingResponseBatches_GetFromSinglePatient", RequestNamespace="http://www.axialabs.com/", ResponseNamespace="http://www.axialabs.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public WS_HospitalRatingResponseBatches_GetFromSinglePatient_Response route_HospitalRatingResponseBatches_GetFromSinglePatient(WS_HospitalRatingResponseBatches_GetFromSinglePatient_Request batchIdentifier) {
            object[] results = this.Invoke("route_HospitalRatingResponseBatches_GetFromSinglePatient", new object[] {
                        batchIdentifier});
            return ((WS_HospitalRatingResponseBatches_GetFromSinglePatient_Response)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginroute_HospitalRatingResponseBatches_GetFromSinglePatient(WS_HospitalRatingResponseBatches_GetFromSinglePatient_Request batchIdentifier, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("route_HospitalRatingResponseBatches_GetFromSinglePatient", new object[] {
                        batchIdentifier}, callback, asyncState);
        }
        
        /// <remarks/>
        public WS_HospitalRatingResponseBatches_GetFromSinglePatient_Response Endroute_HospitalRatingResponseBatches_GetFromSinglePatient(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((WS_HospitalRatingResponseBatches_GetFromSinglePatient_Response)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.axialabs.com/route_HospitalRatingResponses_GetFromSingleHospital", RequestNamespace="http://www.axialabs.com/", ResponseNamespace="http://www.axialabs.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public WS_HospitalRatingResponses_GetFromSingleHospital_Response route_HospitalRatingResponses_GetFromSingleHospital(WS_HospitalRatingResponses_GetFromSingleHospital_Request responseSetIdentifier) {
            object[] results = this.Invoke("route_HospitalRatingResponses_GetFromSingleHospital", new object[] {
                        responseSetIdentifier});
            return ((WS_HospitalRatingResponses_GetFromSingleHospital_Response)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginroute_HospitalRatingResponses_GetFromSingleHospital(WS_HospitalRatingResponses_GetFromSingleHospital_Request responseSetIdentifier, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("route_HospitalRatingResponses_GetFromSingleHospital", new object[] {
                        responseSetIdentifier}, callback, asyncState);
        }
        
        /// <remarks/>
        public WS_HospitalRatingResponses_GetFromSingleHospital_Response Endroute_HospitalRatingResponses_GetFromSingleHospital(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((WS_HospitalRatingResponses_GetFromSingleHospital_Response)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.axialabs.com/")]
    public partial class WS_Patient_AddNew_Request {
        
        /// <remarks/>
        public string patientRef;
        
        /// <remarks/>
        public string title;
        
        /// <remarks/>
        public string surname;
        
        /// <remarks/>
        public string firstName;
        
        /// <remarks/>
        public System.DateTime birthDate;
        
        /// <remarks/>
        public string nationalIdentificationNumber;
        
        /// <remarks/>
        public string contactEmail;
        
        /// <remarks/>
        public string contactAddress;
        
        /// <remarks/>
        public string contactAddressState;
        
        /// <remarks/>
        public string contactTelephone;
        
        /// <remarks/>
        public string contactTelephone2;
        
        /// <remarks/>
        public string contactTelephone3;
        
        /// <remarks/>
        public string occupation;
        
        /// <remarks/>
        public string insuranceIdentificationNumber;
        
        /// <remarks/>
        public string photograph;
        
        /// <remarks/>
        public string signature;
        
        /// <remarks/>
        public string password;
        
        /// <remarks/>
        public string gender;
        
        /// <remarks/>
        public string remark3;
        
        /// <remarks/>
        public string remark4;
        
        /// <remarks/>
        public string remark5;
        
        /// <remarks/>
        public string remark6;
        
        /// <remarks/>
        public string remark7;
        
        /// <remarks/>
        public string remark8;
        
        /// <remarks/>
        public string remark9;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.axialabs.com/")]
    public partial class WS_HospitalRatingResponses_GetFromSingleHospital_Response {
        
        /// <remarks/>
        public int responseCode;
        
        /// <remarks/>
        public HospitalRatingResponse[] hospitalRatingResponses;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.axialabs.com/")]
    public partial class HospitalRatingResponse {
        
        /// <remarks/>
        public int hospitalRatingResponseId;
        
        /// <remarks/>
        public string hospitalRatingResponseRef;
        
        /// <remarks/>
        public string hospitalRef;
        
        /// <remarks/>
        public string patientRef;
        
        /// <remarks/>
        public string hospitalRatingTitle;
        
        /// <remarks/>
        public string hospitalRatingResponse;
        
        /// <remarks/>
        public string remark1;
        
        /// <remarks/>
        public string remark2;
        
        /// <remarks/>
        public string remark3;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.axialabs.com/")]
    public partial class WS_HospitalRatingResponses_GetFromSingleHospital_Request {
        
        /// <remarks/>
        public string hospitalRef;
        
        /// <remarks/>
        public string patientRef;
        
        /// <remarks/>
        public System.DateTime dateTimeStamp;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.axialabs.com/")]
    public partial class HospitalRatingResponseBatch {
        
        /// <remarks/>
        public string hospitalRef;
        
        /// <remarks/>
        public string hospitalName;
        
        /// <remarks/>
        public string patientRef;
        
        /// <remarks/>
        public string dateTimeStamp;
        
        /// <remarks/>
        public System.DateTime dateTimeStampRaw;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.axialabs.com/")]
    public partial class WS_HospitalRatingResponseBatches_GetFromSinglePatient_Response {
        
        /// <remarks/>
        public int responseCode;
        
        /// <remarks/>
        public HospitalRatingResponseBatch[] hospitalRatingResponseBatches;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.axialabs.com/")]
    public partial class WS_HospitalRatingResponseBatches_GetFromSinglePatient_Request {
        
        /// <remarks/>
        public string patientRef;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.axialabs.com/")]
    public partial class Hospital {
        
        /// <remarks/>
        public int hospitalId;
        
        /// <remarks/>
        public string hospitalRef;
        
        /// <remarks/>
        public string hospitalName;
        
        /// <remarks/>
        public string hospitalDescription;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.axialabs.com/")]
    public partial class WS_Hospitals_GetAll_Response {
        
        /// <remarks/>
        public int responseCode;
        
        /// <remarks/>
        public Hospital[] hospitals;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.axialabs.com/")]
    public partial class HospitalRating {
        
        /// <remarks/>
        public int hospitalRatingId;
        
        /// <remarks/>
        public string hospitalRatingGroup;
        
        /// <remarks/>
        public string hospitalRatingDepartment;
        
        /// <remarks/>
        public string hospitalRatingTitle;
        
        /// <remarks/>
        public string remark1;
        
        /// <remarks/>
        public string remark2;
        
        /// <remarks/>
        public string remark3;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.axialabs.com/")]
    public partial class WS_HospitalRatings_GetAll_Response {
        
        /// <remarks/>
        public int responseCode;
        
        /// <remarks/>
        public HospitalRating[] hospitalRatings;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.axialabs.com/")]
    public partial class WS_HospitalRatingResponse_Get_Response {
        
        /// <remarks/>
        public int responseCode;
        
        /// <remarks/>
        public HospitalRatingResponse hospitalRatingResponse;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.axialabs.com/")]
    public partial class WS_HospitalRatingResponse_Get_Request {
        
        /// <remarks/>
        public string hospitalRatingResponseRef;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.axialabs.com/")]
    public partial class WS_HospitalRatingAssessment_AddNew_Response {
        
        /// <remarks/>
        public int responseCode;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.axialabs.com/")]
    public partial class WS_HospitalRatingAssessment_AddNew_Request {
        
        /// <remarks/>
        public HospitalRatingResponse[] hospitalRatingResponses;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.axialabs.com/")]
    public partial class WS_Patient_Update_Response {
        
        /// <remarks/>
        public int responseCode;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.axialabs.com/")]
    public partial class WS_Patient_Update_Request {
        
        /// <remarks/>
        public string patientRef;
        
        /// <remarks/>
        public string title;
        
        /// <remarks/>
        public string surname;
        
        /// <remarks/>
        public string firstName;
        
        /// <remarks/>
        public System.DateTime birthDate;
        
        /// <remarks/>
        public string nationalIdentificationNumber;
        
        /// <remarks/>
        public string contactEmail;
        
        /// <remarks/>
        public string contactAddress;
        
        /// <remarks/>
        public string contactAddressState;
        
        /// <remarks/>
        public string contactTelephone;
        
        /// <remarks/>
        public string contactTelephone2;
        
        /// <remarks/>
        public string contactTelephone3;
        
        /// <remarks/>
        public string occupation;
        
        /// <remarks/>
        public string insuranceIdentificationNumber;
        
        /// <remarks/>
        public string photograph;
        
        /// <remarks/>
        public string signature;
        
        /// <remarks/>
        public string password;
        
        /// <remarks/>
        public string gender;
        
        /// <remarks/>
        public string remark3;
        
        /// <remarks/>
        public string remark4;
        
        /// <remarks/>
        public string remark5;
        
        /// <remarks/>
        public string remark6;
        
        /// <remarks/>
        public string remark7;
        
        /// <remarks/>
        public string remark8;
        
        /// <remarks/>
        public string remark9;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.axialabs.com/")]
    public partial class WS_Patient_GetByEmail_Response {
        
        /// <remarks/>
        public int responseCode;
        
        /// <remarks/>
        public Patient patient;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.axialabs.com/")]
    public partial class Patient {
        
        /// <remarks/>
        public int patientId;
        
        /// <remarks/>
        public string patientRef;
        
        /// <remarks/>
        public string title;
        
        /// <remarks/>
        public string surname;
        
        /// <remarks/>
        public string firstName;
        
        /// <remarks/>
        public System.DateTime birthDate;
        
        /// <remarks/>
        public string nationalIdentificationNumber;
        
        /// <remarks/>
        public string contactEmail;
        
        /// <remarks/>
        public string contactAddress;
        
        /// <remarks/>
        public string contactAddressState;
        
        /// <remarks/>
        public string contactTelephone;
        
        /// <remarks/>
        public string contactTelephone2;
        
        /// <remarks/>
        public string contactTelephone3;
        
        /// <remarks/>
        public string occupation;
        
        /// <remarks/>
        public string insuranceIdentificationNumber;
        
        /// <remarks/>
        public string photograph;
        
        /// <remarks/>
        public string signature;
        
        /// <remarks/>
        public string password;
        
        /// <remarks/>
        public string gender;
        
        /// <remarks/>
        public string remark3;
        
        /// <remarks/>
        public string remark4;
        
        /// <remarks/>
        public string remark5;
        
        /// <remarks/>
        public string remark6;
        
        /// <remarks/>
        public string remark7;
        
        /// <remarks/>
        public string remark8;
        
        /// <remarks/>
        public string remark9;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.axialabs.com/")]
    public partial class WS_Patient_GetByEmail_Request {
        
        /// <remarks/>
        public string contactEmail;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.axialabs.com/")]
    public partial class WS_Patient_GetByPatientRef_Response {
        
        /// <remarks/>
        public int responseCode;
        
        /// <remarks/>
        public Patient patient;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.axialabs.com/")]
    public partial class WS_Patient_GetByPatientRef_Request {
        
        /// <remarks/>
        public string patientRef;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.axialabs.com/")]
    public partial class WS_Login_Response {
        
        /// <remarks/>
        public int responseCode;
        
        /// <remarks/>
        public string patientRef;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.axialabs.com/")]
    public partial class WS_Login_Request {
        
        /// <remarks/>
        public string username;
        
        /// <remarks/>
        public string password;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.axialabs.com/")]
    public partial class WS_Patient_AddNew_Response {
        
        /// <remarks/>
        public int responseCode;
    }
}
